name: CI

on:
    push:
        branches:
            - development
    pull_request:
        branches:
            - development

jobs:
    compile:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code into workspace directory
              uses: actions/checkout@v2
            - name: Install project dependencies
              uses: docker://dataformco/dataform:latest
              with:
                  args: install
            - name: Run dataform compile
              uses: docker://dataformco/dataform:latest
              with:
                  args: compile
            - name: Decrypt dataform credentials
              run: gpg --quiet --batch --yes --decrypt --passphrase="$CREDENTIALS_GPG_PASSPHRASE" --output .df-credentials.json .df-credentials.json.gpg
              env:
                  CREDENTIALS_GPG_PASSPHRASE: ${{ secrets.CREDENTIALS_GPG_PASSPHRASE }}
            - name: Run dataform test
              uses: docker://dataformco/dataform:latest
              with:
                  args: test
